FROM node:20.10.0 AS BUID_IMAGE
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=BUID_IMAGE /app ./
# COPY --from=BUID_IMAGE /app/node_modules ./node_modules
CMD [ "npm", "start" ]