# # .github/workflows/second_cd.yml
# name: Deploy to AWS

# on:
#   workflow_run:
#     workflows: [Build and Push Docker Images to Dockerhub]
#     types:
#       - completed

# jobs:
#   success:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#       - run: echo 'Docker image build and push successfully.'
#       # - name: remove old images from aws
#       #   run: |
#       #     docker rmi --force eshan3312/mern-food-delivery-frontend-action:latest || true
#       #     docker rmi --force eshan3312/mern-food-delivery-backend-action:latest || true
#       # - name: scan docker image with trivy
#       #   run: |
#       #     trivy image eshan3312/mern-food-delivery-frontend-action:latest
#       #     trivy image eshan3312/mern-food-delivery-backend-action:latest
#       # - name: create new deployment to aws
#       #   run: |
#       #     docker-compose build --pull --no-cache
#       #     docker-compose up -d --force-recreate
#       #     docker ps
#   failure:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       - run: echo 'Docker image build and push failed.'
#   exit:
#     needs: failure
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1
#   deploy:
#     needs: success
#     runs-on: ubuntu-latest
#     steps:
#     - name: remove old images and create new deployment
#       run: |
#         docker rmi --force eshan3312/mern-food-delivery-frontend-action:latest || true
#         docker rmi --force eshan3312/mern-food-delivery-backend-action:latest || true
#     - name: scan image with trivy
#       run: |
#         trivy image eshan3312/mern-food-delivery-frontend-action:latest
#         trivy image eshan3312/mern-food-delivery-backend-action:latest
#     - name: create new deployment
#       run: |
#         docker-compose build --pull --no-cache
#         docker-compose up -d --force-recreate
#         docker ps
